name: Snyk Terraform IaC Scan (No Block)

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  snyk-iac:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Snyk IaC scan (non-blocking)
        uses: snyk/actions/iac@v1
        continue-on-error: true        # prevents pipeline failure
        env:
          SNYK_TOKEN: aed514c5-df9e-40d2-8cfc-51990b7a3cde
        with:
          args: >
            test .
            --severity-threshold=low
            --sarif-file-output=snyk-terraform.sarif

      - name: Verify SARIF file
        run: |
          if [ -f snyk-terraform.sarif ]; then
            echo "SARIF generated successfully"
          else
            echo "SARIF NOT FOUND"
            exit 1
          fi

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-terraform.sarif
